# Let's see if we can inflate under the null

```{r libraries}
## For running the simulations and plotting the results the following
## packages have to be loaded:
library(parallel)
## devtools::install_github('floatofmath/blindConfidence')
library(blindConfidence)
library(ggplot2)
library(reshape2)
library(plyr)
library(pander)
options(mc.cores=min(10,detectCores()-1))
``` 
```{r load data maximum bias,eval=T,echo=F}

data(maxsim)

full.sim <- maxsim
maxsim$ylow <- 0

```

```{r plot labeller,results='hide',include=F,echo=F}
                                        #This little function takes care of annotating the plots.
lverbose  <- function(labels,from=c("anc","mmb","mvb"),to=c("AC-NC [%]","max. mean bias","abs. variance bias"),multi_line=TRUE){
    str_labels <- label_value(labels,multi_line)
    par_labels <- label_parsed(labels,multi_line)
    strings <- grep("str_",str_labels[[1]])
    str_labels[[1]] <- sub("str_","",str_labels[[1]])
    if(!is.null(from)){
        str_labels[[1]] <- mapvalues(str_labels[[1]],from,to)
    }
    par_labels[[1]][strings] <- str_labels[[1]][strings]
    return(par_labels)
}


```


```{r,eval=F}
maxcoverageopt0 <- select_results(subset(maxsim,delta==0),c('total.prob','upper.prob','uc.total.prob','uc.upper.prob'),base_columns=c('n1','tn1','delta','sigma','d','s'),functional=which.max)

G2coverage <- add_epsilon(maxcoverageopt0,.2,.005,c('sigma'))
plot_grid(maxsim,maxcoverageopt0,G2coverage,'sigma')
options(mc.cores=min(20,detectCores()-1))
maxcoveragesim02 <- simulate_batch(data.frame(G2coverage),4*10^6,use=T)
##save(maxcoveragesim02,file="nullsim.rda")
load("nullsim.rda")
## reshape and resim
maxcoverageopt02 <- select_results(maxcoveragesim02,c('total.prob','upper.prob','uc.total.prob','uc.upper.prob'),base_columns=c('n1','tn1','delta','sigma','d','s'),functional=which.max)
options(mc.cores=min(16,detectCores()-1))
maxcoveragesim03 <- simulate_batch(data.frame(maxcoverageopt02),10^7,use=T)
fname <- paste('~/newBlindedResults/resim_coverage0',Sys.info()['nodename'],'_',format(Sys.time(),"%y%m%d"),'.Rd',sep='')
save(maxcoveragesim03,file=fname)



```

```{r,echo=F,results='hide'}
load("~/srv-home/newBlindedResults/resim_coverage0node1_160127.Rd")

max.coverage2 <- ddply(maxcoveragesim03,"n1",transform,
                       max.twosided= -(total.prob-.05),
                       uc.max.twosided = -(uc.total.prob-.05),
                       max.onesided= -(upper.prob-.025),
                       uc.max.onesided = -(uc.upper.prob-.025),
                       method=c("upper.prob"="adjusted","uc.upper.prob"="unadjusted","total.prob"="adjusted","uc.total.prob"="unadjusted")[what.max],
                       side=c("total.prob"="two-sided","uc.total.prob"="two-sided","upper.prob"="one-sided","uc.upper.prob"="one-sided")[what.max]
                  )

max.coverage2 <- max.coverage2[,c('method','side','n1','delta','sigma','max.twosided','uc.max.twosided','max.onesided','uc.max.onesided')]

```

```{r maxCoverage,echo=F,fig.width=5,fig.height=5,fig.cap="\\label{fig:maxvar} Maximum (absolute) difference between actual and nominal coverage probabilities for a given per group first stage sample sizes $n_1$ between $2$ and $50$. Left column shows the results for the unadjusted sample size reassessment rule, right column for the adjusted sample size reassessment rule. The first row shows the difference between actual and nominal coverage probabilities, the second the effect size $\\delta$ and the third the standard deviation $\\sigma$ at which the specific value is attained. The blue line denotes a Loess smoothed estimate.",fig.align='center'}
df <- melt(max.coverage2,id=c('n1','method','side'))
df <- subset(df,!(method=='adjusted' & variable %in% c('uc.max.onesided','uc.max.twosided')))
df <- subset(df,!(method=='unadjusted' & variable %in% c('max.onesided','max.twosided')))
df <- subset(df,!(side=='one-sided' & variable %in% c('uc.max.twosided','max.twosided')))
df <- subset(df,!(side=='two-sided' & variable %in% c('max.onesided','uc.max.onesided')))
df <- within(df,scale <- c("absolute","relative")[grepl("rel",variable)+1])
df <- within(df,variable <- sub("rel\\.","",variable))
df <- within(df,variable <- sub("uc\\.","",variable))
df <- df[df$variable %in% c('max.onesided','max.twosided','delta','sigma'),]
df <- within(df,variable <- sub("(onesided)|(twosided)","coverage",variable))
df <- within(df,variable <- factor(variable))
df <- within(df,variable <- revalue(variable,c('max.coverage'='str_anc','delta'=expression(delta),'sigma'=expression(sigma))))
df <- within(df,variable <- relevel(variable,'delta'))
df <- within(df,variable <- relevel(variable,'str_anc'))
df <- within(df,method <- relevel(method,'unadjusted'))

dfa <- df[df$scale=="absolute",]#"relative",]#
scalehelper <- data.frame(n1=rep(-10,6),variable=factor(1:3,label=c("str_anc","delta","sigma")),value=rep(0,6),scale=rep("absolute",3),method=rep("adjusted",3),side=rep(c('one-sided','two-sided'),each=3))
dfa <- rbind(dfa,scalehelper)

cplot <- ggplot(dfa) +
    geom_line(aes(n1,100*value,linetype=side,shape=side),data=subset(dfa,variable=="str_anc")) +
        geom_smooth(aes(n1,value),data=subset(dfa,variable!="str_anc")) +
            geom_point(aes(n1,value,shape=side),data=subset(dfa,variable!="str_anc"),size=.5) +
                facet_grid(variable~method,scale='free_y',labeller=lverbose)+xlab(expression(n[1]))+ylab('')+theme_bw()+xlim(c(2,50))


print(cplot)
    
pdf("~/srv-home/newBlindedResults/nullsim.pdf")
print(cplot)
dev.off()

```



